# -*- coding: utf-8 -*-
"""exctraction_questions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-khtsbxCTkIXG9oQxeoEyqmOXyyt5Ila
"""

import os
import openpyxl
import re

from google.colab import drive
drive.mount('/content/drive')

txt_file_path = '/content/drive/MyDrive/questions/corpus_3rd.txt'

with open(txt_file_path, 'r') as file:
    content = file.read()

pattern = r'(HV1|PAR)(.*?)\?'

matches = re.findall(pattern, content)

questions = [match[0] + match[1].strip() + '?' for match in matches]

excel_file = '/content/drive/MyDrive/questions/corpustxt_3rd.xlsx'

workbook = openpyxl.Workbook()
sheet = workbook.active

for i, question in enumerate(questions, start=1):
    sheet.cell(row=i, column=1, value=question)

workbook.save(excel_file)
